[libdefaults]
    default_realm = __REALM__
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 7d
    renew_lifetime = 14d
    forwardable = true

[realms]
    __REALM__ = {
        kdc = __KDC__
        admin_server = __KADMIN__
    }

[domain_realm]
    .__DOMAIN__ = __REALM__
    __DOMAIN__ = __REALM__
