[libdefaults]
    default_realm = __REALM__
    kdc_timesync = 1
    ccache_type = 4
    forwardable = true
    proxiable = true
    fcc-mit-ticket-flags = true
    ticket_lifetime = 7d
    renew_lifetime = 14d
[realms]
    __REALM__ = {
        kdc = __KDC__
        admin_server = __KADMIN__
        auth_to_local = DEFAULT
    }
[domain_realm]
    .__DOMAIN__ = __REALM__
    __DOMAIN__ = __REALM__
