[domain/__DOMAIN__]
ldap_schema = rfc2307bis
ldap_group_nesting_level = 1000
ldap_default_bind_dn = __SSSD_BIND_DN__
ldap_default_authtok = __SSSD_PASSWORD__
ldap_default_authtok_type = obfuscated_password
id_provider = ldap
ldap_uri = __URI__
ldap_search_base = __LDAP_SEARCH_BASE__
ldap_user_search_base = __LDAP_USER_BASE__
ldap_group_search_base = __LDAP_GROUP_BASE__
ldap_id_use_start_tls = false
